apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deploy.name }}
spec:
  selector:
    matchLabels:
      dep: {{ .Values.deploy.label.dep }}
  replicas: 3
  template:
    metadata:
      labels:
        dep: {{ .Values.deploy.label.dep }}
    spec:
      containers:
      - name: {{ .Values.container.name }}
        image: '{{ .Values.image.repository }}:{{ .Values.image.tag }}'
        env:
        - name: 'PORT'
          value: '{{ .Values.container.port }}'
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - all
            add: ["MKNOD"]
        livenessProbe:
          exec:
            command:
            - cat
            - /usr/share/nginx/html/index.html
          initialDelaySeconds: 5
          periodSeconds: 5