apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: NodePort
  selector:
    dep: {{ .Values.deploy.label.dep }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.container.port }}