apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.container.name }}-service
spec:
  type: NodePort
  selector:
    repo: bpcalc
  ports:
  - protocol: TCP
    port: 80
    targetPort: {{ .Values.container.port }}