name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

#env:
  #SONAR_ORG: hypheni
  #SONAR_PROJ: go-bp-calc-k8s
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      # Git checkout
      - name: Checkout
        uses: actions/checkout@v3
        
      # Setup Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
          #cache-dependency-path: subdir/package-lock.json
      
      # Fetch Dependencies
      - name: Dependency
        run: npm ci
      
      # # Build
      # - name: Code Build
      #   run: npm run build

      # # Unit Test
      # - name: Unit Test
      #   run: npm test

      # # SAST analysis
      # - name: SonarCloud Analysis
      #   uses: actions/cache@v2
      #   with:
      #     path: ~/.sonar/cache
      #     key: ${{ runner.os }}-sonar
      #     restore-keys: ${{ runner.os }}-sonar
      # - uses: SonarSource/sonarcloud-github-action@v1.8
      #   env:
      #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      #   with:
      #     args:
      #       -Dsonar.projectKey=react-bp-microservice
      #       -Dsonar.organization=hypheni
      #       -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info

      # Node package vulnerability check
      # - name: Vulnerability Check
      #   uses: NodeSecure/ci-action@177c57fe32c75cafabe87f6e4515d277cc37ae6c #1.4.1
      #   with:
      #     strategy: npm
      #     vulnerabilities: medium
      #     warnings: off
      #     reporters: console

      # Node vulnarability scan using Synk
      - name: Vulnerability Check with Synk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      
      - name: Upload Synk result to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif