name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

#env:
  #SONAR_ORG: hypheni
  #SONAR_PROJ: go-bp-calc-k8s
  
jobs:
  integration:
    permissions:
      contents: read
      security-events: write

    runs-on: ubuntu-22.04

    steps:
      # Git Checkout
      - name: Checkout
        uses: actions/checkout@v3
        
      # Setup Node
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 19
          cache: 'npm'
      
      # Install Node Dependencies
      - name: Dependency
        run: npm ci
      
      # Unit Test
      - name: Unit Test
        run: npm test

      # Sonar Static Code Analysis
      - name: SonarCloud Analysis
        uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - uses: SonarSource/sonarcloud-github-action@v1.8
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=react-bp-microservice
            -Dsonar.organization=hypheni
            -Dsonar.javascript.lcov.reportPaths=./coverage/lcov.info

      # Synk Vulnarability Scan for Node Packages
      # TODO: --dev parameter shall be used for a dev run only
      - name: Vulnerability Check with Synk
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
                --severity-threshold=high
                # --dev
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
